package(default_visibility = ["//visibility:public"])

# ChunkBuffer is a wrapper around a queue, no need to test
cc_library(
    name = "chunk_buffer",
    srcs = ["chunk_buffer.cc"],
    hdrs = ["chunk_buffer.hh"],
)
