// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio Video Initial Packet Host Protocol.proto

package Nick_Stuff.Protocols;

public final class AVInitHP {
  private AVInitHP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 proto_type = 1;</code>
     */
    boolean hasProtoType();
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    int getProtoType();

    /**
     * <code>required int64 proto_id = 2;</code>
     */
    boolean hasProtoId();
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    long getProtoId();

    /**
     * <code>required int64 utc_time = 3;</code>
     */
    boolean hasUtcTime();
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    long getUtcTime();

    /**
     * <pre>
     *Video Information
     * </pre>
     *
     * <code>required bytes PPS = 4;</code>
     */
    boolean hasPPS();
    /**
     * <pre>
     *Video Information
     * </pre>
     *
     * <code>required bytes PPS = 4;</code>
     */
    com.google.protobuf.ByteString getPPS();

    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor> 
        getMonitorsList();
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    Nick_Stuff.Protocols.AVInitHP.request.monitor getMonitors(int index);
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    int getMonitorsCount();
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    java.util.List<? extends Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder> 
        getMonitorsOrBuilderList();
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder getMonitorsOrBuilder(
        int index);

    /**
     * <code>required int32 vid_bitrate = 6;</code>
     */
    boolean hasVidBitrate();
    /**
     * <code>required int32 vid_bitrate = 6;</code>
     */
    int getVidBitrate();

    /**
     * <code>required int32 framerate = 7;</code>
     */
    boolean hasFramerate();
    /**
     * <code>required int32 framerate = 7;</code>
     */
    int getFramerate();

    /**
     * <pre>
     *Audio Information
     * </pre>
     *
     * <code>required int32 samplerate = 8;</code>
     */
    boolean hasSamplerate();
    /**
     * <pre>
     *Audio Information
     * </pre>
     *
     * <code>required int32 samplerate = 8;</code>
     */
    int getSamplerate();

    /**
     * <code>required int32 audio_bitrate = 9;</code>
     */
    boolean hasAudioBitrate();
    /**
     * <code>required int32 audio_bitrate = 9;</code>
     */
    int getAudioBitrate();

    /**
     * <code>required int32 channelcount = 10;</code>
     */
    boolean hasChannelcount();
    /**
     * <code>required int32 channelcount = 10;</code>
     */
    int getChannelcount();

    /**
     * <code>required int64 channellayout = 11;</code>
     */
    boolean hasChannellayout();
    /**
     * <code>required int64 channellayout = 11;</code>
     */
    long getChannellayout();
  }
  /**
   * Protobuf type {@code request}
   */
  public  static final class request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:request)
      requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use request.newBuilder() to construct.
    private request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private request() {
      protoType_ = 0;
      protoId_ = 0L;
      utcTime_ = 0L;
      pPS_ = com.google.protobuf.ByteString.EMPTY;
      monitors_ = java.util.Collections.emptyList();
      vidBitrate_ = 0;
      framerate_ = 0;
      samplerate_ = 0;
      audioBitrate_ = 0;
      channelcount_ = 0;
      channellayout_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              protoId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              utcTime_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pPS_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                monitors_ = new java.util.ArrayList<Nick_Stuff.Protocols.AVInitHP.request.monitor>();
                mutable_bitField0_ |= 0x00000010;
              }
              monitors_.add(
                  input.readMessage(Nick_Stuff.Protocols.AVInitHP.request.monitor.PARSER, extensionRegistry));
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              vidBitrate_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              framerate_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              samplerate_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              audioBitrate_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              channelcount_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000200;
              channellayout_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          monitors_ = java.util.Collections.unmodifiableList(monitors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Nick_Stuff.Protocols.AVInitHP.internal_static_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Nick_Stuff.Protocols.AVInitHP.internal_static_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Nick_Stuff.Protocols.AVInitHP.request.class, Nick_Stuff.Protocols.AVInitHP.request.Builder.class);
    }

    public interface monitorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:request.monitor)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 height = 1;</code>
       */
      boolean hasHeight();
      /**
       * <code>required int32 height = 1;</code>
       */
      int getHeight();

      /**
       * <code>required int32 width = 2;</code>
       */
      boolean hasWidth();
      /**
       * <code>required int32 width = 2;</code>
       */
      int getWidth();

      /**
       * <code>required bool availability = 3 [default = true];</code>
       */
      boolean hasAvailability();
      /**
       * <code>required bool availability = 3 [default = true];</code>
       */
      boolean getAvailability();
    }
    /**
     * Protobuf type {@code request.monitor}
     */
    public  static final class monitor extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:request.monitor)
        monitorOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use monitor.newBuilder() to construct.
      private monitor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private monitor() {
        height_ = 0;
        width_ = 0;
        availability_ = true;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private monitor(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                height_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                width_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                availability_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Nick_Stuff.Protocols.AVInitHP.internal_static_request_monitor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Nick_Stuff.Protocols.AVInitHP.internal_static_request_monitor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Nick_Stuff.Protocols.AVInitHP.request.monitor.class, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder.class);
      }

      private int bitField0_;
      public static final int HEIGHT_FIELD_NUMBER = 1;
      private int height_;
      /**
       * <code>required int32 height = 1;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 height = 1;</code>
       */
      public int getHeight() {
        return height_;
      }

      public static final int WIDTH_FIELD_NUMBER = 2;
      private int width_;
      /**
       * <code>required int32 width = 2;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 width = 2;</code>
       */
      public int getWidth() {
        return width_;
      }

      public static final int AVAILABILITY_FIELD_NUMBER = 3;
      private boolean availability_;
      /**
       * <code>required bool availability = 3 [default = true];</code>
       */
      public boolean hasAvailability() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool availability = 3 [default = true];</code>
       */
      public boolean getAvailability() {
        return availability_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasHeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWidth()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAvailability()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, height_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, width_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, availability_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, height_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, width_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, availability_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Nick_Stuff.Protocols.AVInitHP.request.monitor)) {
          return super.equals(obj);
        }
        Nick_Stuff.Protocols.AVInitHP.request.monitor other = (Nick_Stuff.Protocols.AVInitHP.request.monitor) obj;

        boolean result = true;
        result = result && (hasHeight() == other.hasHeight());
        if (hasHeight()) {
          result = result && (getHeight()
              == other.getHeight());
        }
        result = result && (hasWidth() == other.hasWidth());
        if (hasWidth()) {
          result = result && (getWidth()
              == other.getWidth());
        }
        result = result && (hasAvailability() == other.hasAvailability());
        if (hasAvailability()) {
          result = result && (getAvailability()
              == other.getAvailability());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasHeight()) {
          hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
          hash = (53 * hash) + getHeight();
        }
        if (hasWidth()) {
          hash = (37 * hash) + WIDTH_FIELD_NUMBER;
          hash = (53 * hash) + getWidth();
        }
        if (hasAvailability()) {
          hash = (37 * hash) + AVAILABILITY_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getAvailability());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.AVInitHP.request.monitor parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Nick_Stuff.Protocols.AVInitHP.request.monitor prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code request.monitor}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:request.monitor)
          Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Nick_Stuff.Protocols.AVInitHP.internal_static_request_monitor_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Nick_Stuff.Protocols.AVInitHP.internal_static_request_monitor_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Nick_Stuff.Protocols.AVInitHP.request.monitor.class, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder.class);
        }

        // Construct using Nick_Stuff.Protocols.AVInitHP.request.monitor.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          height_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          width_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          availability_ = true;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Nick_Stuff.Protocols.AVInitHP.internal_static_request_monitor_descriptor;
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.AVInitHP.request.monitor getDefaultInstanceForType() {
          return Nick_Stuff.Protocols.AVInitHP.request.monitor.getDefaultInstance();
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.AVInitHP.request.monitor build() {
          Nick_Stuff.Protocols.AVInitHP.request.monitor result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.AVInitHP.request.monitor buildPartial() {
          Nick_Stuff.Protocols.AVInitHP.request.monitor result = new Nick_Stuff.Protocols.AVInitHP.request.monitor(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.height_ = height_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.width_ = width_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.availability_ = availability_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Nick_Stuff.Protocols.AVInitHP.request.monitor) {
            return mergeFrom((Nick_Stuff.Protocols.AVInitHP.request.monitor)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Nick_Stuff.Protocols.AVInitHP.request.monitor other) {
          if (other == Nick_Stuff.Protocols.AVInitHP.request.monitor.getDefaultInstance()) return this;
          if (other.hasHeight()) {
            setHeight(other.getHeight());
          }
          if (other.hasWidth()) {
            setWidth(other.getWidth());
          }
          if (other.hasAvailability()) {
            setAvailability(other.getAvailability());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasHeight()) {
            return false;
          }
          if (!hasWidth()) {
            return false;
          }
          if (!hasAvailability()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Nick_Stuff.Protocols.AVInitHP.request.monitor parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Nick_Stuff.Protocols.AVInitHP.request.monitor) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int height_ ;
        /**
         * <code>required int32 height = 1;</code>
         */
        public boolean hasHeight() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 height = 1;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>required int32 height = 1;</code>
         */
        public Builder setHeight(int value) {
          bitField0_ |= 0x00000001;
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 height = 1;</code>
         */
        public Builder clearHeight() {
          bitField0_ = (bitField0_ & ~0x00000001);
          height_ = 0;
          onChanged();
          return this;
        }

        private int width_ ;
        /**
         * <code>required int32 width = 2;</code>
         */
        public boolean hasWidth() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 width = 2;</code>
         */
        public int getWidth() {
          return width_;
        }
        /**
         * <code>required int32 width = 2;</code>
         */
        public Builder setWidth(int value) {
          bitField0_ |= 0x00000002;
          width_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 width = 2;</code>
         */
        public Builder clearWidth() {
          bitField0_ = (bitField0_ & ~0x00000002);
          width_ = 0;
          onChanged();
          return this;
        }

        private boolean availability_ = true;
        /**
         * <code>required bool availability = 3 [default = true];</code>
         */
        public boolean hasAvailability() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bool availability = 3 [default = true];</code>
         */
        public boolean getAvailability() {
          return availability_;
        }
        /**
         * <code>required bool availability = 3 [default = true];</code>
         */
        public Builder setAvailability(boolean value) {
          bitField0_ |= 0x00000004;
          availability_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool availability = 3 [default = true];</code>
         */
        public Builder clearAvailability() {
          bitField0_ = (bitField0_ & ~0x00000004);
          availability_ = true;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:request.monitor)
      }

      // @@protoc_insertion_point(class_scope:request.monitor)
      private static final Nick_Stuff.Protocols.AVInitHP.request.monitor DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Nick_Stuff.Protocols.AVInitHP.request.monitor();
      }

      public static Nick_Stuff.Protocols.AVInitHP.request.monitor getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<monitor>
          PARSER = new com.google.protobuf.AbstractParser<monitor>() {
        @java.lang.Override
        public monitor parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new monitor(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<monitor> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<monitor> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.AVInitHP.request.monitor getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PROTO_TYPE_FIELD_NUMBER = 1;
    private int protoType_;
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    public int getProtoType() {
      return protoType_;
    }

    public static final int PROTO_ID_FIELD_NUMBER = 2;
    private long protoId_;
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    public boolean hasProtoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    public long getProtoId() {
      return protoId_;
    }

    public static final int UTC_TIME_FIELD_NUMBER = 3;
    private long utcTime_;
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    public boolean hasUtcTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    public long getUtcTime() {
      return utcTime_;
    }

    public static final int PPS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString pPS_;
    /**
     * <pre>
     *Video Information
     * </pre>
     *
     * <code>required bytes PPS = 4;</code>
     */
    public boolean hasPPS() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *Video Information
     * </pre>
     *
     * <code>required bytes PPS = 4;</code>
     */
    public com.google.protobuf.ByteString getPPS() {
      return pPS_;
    }

    public static final int MONITORS_FIELD_NUMBER = 5;
    private java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor> monitors_;
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    public java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor> getMonitorsList() {
      return monitors_;
    }
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    public java.util.List<? extends Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder> 
        getMonitorsOrBuilderList() {
      return monitors_;
    }
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    public int getMonitorsCount() {
      return monitors_.size();
    }
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    public Nick_Stuff.Protocols.AVInitHP.request.monitor getMonitors(int index) {
      return monitors_.get(index);
    }
    /**
     * <code>repeated .request.monitor monitors = 5;</code>
     */
    public Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder getMonitorsOrBuilder(
        int index) {
      return monitors_.get(index);
    }

    public static final int VID_BITRATE_FIELD_NUMBER = 6;
    private int vidBitrate_;
    /**
     * <code>required int32 vid_bitrate = 6;</code>
     */
    public boolean hasVidBitrate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 vid_bitrate = 6;</code>
     */
    public int getVidBitrate() {
      return vidBitrate_;
    }

    public static final int FRAMERATE_FIELD_NUMBER = 7;
    private int framerate_;
    /**
     * <code>required int32 framerate = 7;</code>
     */
    public boolean hasFramerate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 framerate = 7;</code>
     */
    public int getFramerate() {
      return framerate_;
    }

    public static final int SAMPLERATE_FIELD_NUMBER = 8;
    private int samplerate_;
    /**
     * <pre>
     *Audio Information
     * </pre>
     *
     * <code>required int32 samplerate = 8;</code>
     */
    public boolean hasSamplerate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *Audio Information
     * </pre>
     *
     * <code>required int32 samplerate = 8;</code>
     */
    public int getSamplerate() {
      return samplerate_;
    }

    public static final int AUDIO_BITRATE_FIELD_NUMBER = 9;
    private int audioBitrate_;
    /**
     * <code>required int32 audio_bitrate = 9;</code>
     */
    public boolean hasAudioBitrate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 audio_bitrate = 9;</code>
     */
    public int getAudioBitrate() {
      return audioBitrate_;
    }

    public static final int CHANNELCOUNT_FIELD_NUMBER = 10;
    private int channelcount_;
    /**
     * <code>required int32 channelcount = 10;</code>
     */
    public boolean hasChannelcount() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 channelcount = 10;</code>
     */
    public int getChannelcount() {
      return channelcount_;
    }

    public static final int CHANNELLAYOUT_FIELD_NUMBER = 11;
    private long channellayout_;
    /**
     * <code>required int64 channellayout = 11;</code>
     */
    public boolean hasChannellayout() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int64 channellayout = 11;</code>
     */
    public long getChannellayout() {
      return channellayout_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProtoType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtoId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUtcTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPPS()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVidBitrate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFramerate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSamplerate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAudioBitrate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannelcount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannellayout()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMonitorsCount(); i++) {
        if (!getMonitors(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, protoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, utcTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, pPS_);
      }
      for (int i = 0; i < monitors_.size(); i++) {
        output.writeMessage(5, monitors_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, vidBitrate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, framerate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, samplerate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(9, audioBitrate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(10, channelcount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(11, channellayout_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, protoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, utcTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, pPS_);
      }
      for (int i = 0; i < monitors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, monitors_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, vidBitrate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, framerate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, samplerate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, audioBitrate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, channelcount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, channellayout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Nick_Stuff.Protocols.AVInitHP.request)) {
        return super.equals(obj);
      }
      Nick_Stuff.Protocols.AVInitHP.request other = (Nick_Stuff.Protocols.AVInitHP.request) obj;

      boolean result = true;
      result = result && (hasProtoType() == other.hasProtoType());
      if (hasProtoType()) {
        result = result && (getProtoType()
            == other.getProtoType());
      }
      result = result && (hasProtoId() == other.hasProtoId());
      if (hasProtoId()) {
        result = result && (getProtoId()
            == other.getProtoId());
      }
      result = result && (hasUtcTime() == other.hasUtcTime());
      if (hasUtcTime()) {
        result = result && (getUtcTime()
            == other.getUtcTime());
      }
      result = result && (hasPPS() == other.hasPPS());
      if (hasPPS()) {
        result = result && getPPS()
            .equals(other.getPPS());
      }
      result = result && getMonitorsList()
          .equals(other.getMonitorsList());
      result = result && (hasVidBitrate() == other.hasVidBitrate());
      if (hasVidBitrate()) {
        result = result && (getVidBitrate()
            == other.getVidBitrate());
      }
      result = result && (hasFramerate() == other.hasFramerate());
      if (hasFramerate()) {
        result = result && (getFramerate()
            == other.getFramerate());
      }
      result = result && (hasSamplerate() == other.hasSamplerate());
      if (hasSamplerate()) {
        result = result && (getSamplerate()
            == other.getSamplerate());
      }
      result = result && (hasAudioBitrate() == other.hasAudioBitrate());
      if (hasAudioBitrate()) {
        result = result && (getAudioBitrate()
            == other.getAudioBitrate());
      }
      result = result && (hasChannelcount() == other.hasChannelcount());
      if (hasChannelcount()) {
        result = result && (getChannelcount()
            == other.getChannelcount());
      }
      result = result && (hasChannellayout() == other.hasChannellayout());
      if (hasChannellayout()) {
        result = result && (getChannellayout()
            == other.getChannellayout());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtoType()) {
        hash = (37 * hash) + PROTO_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getProtoType();
      }
      if (hasProtoId()) {
        hash = (37 * hash) + PROTO_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProtoId());
      }
      if (hasUtcTime()) {
        hash = (37 * hash) + UTC_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUtcTime());
      }
      if (hasPPS()) {
        hash = (37 * hash) + PPS_FIELD_NUMBER;
        hash = (53 * hash) + getPPS().hashCode();
      }
      if (getMonitorsCount() > 0) {
        hash = (37 * hash) + MONITORS_FIELD_NUMBER;
        hash = (53 * hash) + getMonitorsList().hashCode();
      }
      if (hasVidBitrate()) {
        hash = (37 * hash) + VID_BITRATE_FIELD_NUMBER;
        hash = (53 * hash) + getVidBitrate();
      }
      if (hasFramerate()) {
        hash = (37 * hash) + FRAMERATE_FIELD_NUMBER;
        hash = (53 * hash) + getFramerate();
      }
      if (hasSamplerate()) {
        hash = (37 * hash) + SAMPLERATE_FIELD_NUMBER;
        hash = (53 * hash) + getSamplerate();
      }
      if (hasAudioBitrate()) {
        hash = (37 * hash) + AUDIO_BITRATE_FIELD_NUMBER;
        hash = (53 * hash) + getAudioBitrate();
      }
      if (hasChannelcount()) {
        hash = (37 * hash) + CHANNELCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getChannelcount();
      }
      if (hasChannellayout()) {
        hash = (37 * hash) + CHANNELLAYOUT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getChannellayout());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.AVInitHP.request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Nick_Stuff.Protocols.AVInitHP.request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:request)
        Nick_Stuff.Protocols.AVInitHP.requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Nick_Stuff.Protocols.AVInitHP.internal_static_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Nick_Stuff.Protocols.AVInitHP.internal_static_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Nick_Stuff.Protocols.AVInitHP.request.class, Nick_Stuff.Protocols.AVInitHP.request.Builder.class);
      }

      // Construct using Nick_Stuff.Protocols.AVInitHP.request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMonitorsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        protoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        utcTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        pPS_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (monitorsBuilder_ == null) {
          monitors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          monitorsBuilder_.clear();
        }
        vidBitrate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        framerate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        samplerate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        audioBitrate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        channelcount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        channellayout_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Nick_Stuff.Protocols.AVInitHP.internal_static_request_descriptor;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.AVInitHP.request getDefaultInstanceForType() {
        return Nick_Stuff.Protocols.AVInitHP.request.getDefaultInstance();
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.AVInitHP.request build() {
        Nick_Stuff.Protocols.AVInitHP.request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.AVInitHP.request buildPartial() {
        Nick_Stuff.Protocols.AVInitHP.request result = new Nick_Stuff.Protocols.AVInitHP.request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.protoId_ = protoId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.utcTime_ = utcTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pPS_ = pPS_;
        if (monitorsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            monitors_ = java.util.Collections.unmodifiableList(monitors_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.monitors_ = monitors_;
        } else {
          result.monitors_ = monitorsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vidBitrate_ = vidBitrate_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.framerate_ = framerate_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.samplerate_ = samplerate_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.audioBitrate_ = audioBitrate_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.channelcount_ = channelcount_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.channellayout_ = channellayout_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Nick_Stuff.Protocols.AVInitHP.request) {
          return mergeFrom((Nick_Stuff.Protocols.AVInitHP.request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Nick_Stuff.Protocols.AVInitHP.request other) {
        if (other == Nick_Stuff.Protocols.AVInitHP.request.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasProtoId()) {
          setProtoId(other.getProtoId());
        }
        if (other.hasUtcTime()) {
          setUtcTime(other.getUtcTime());
        }
        if (other.hasPPS()) {
          setPPS(other.getPPS());
        }
        if (monitorsBuilder_ == null) {
          if (!other.monitors_.isEmpty()) {
            if (monitors_.isEmpty()) {
              monitors_ = other.monitors_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMonitorsIsMutable();
              monitors_.addAll(other.monitors_);
            }
            onChanged();
          }
        } else {
          if (!other.monitors_.isEmpty()) {
            if (monitorsBuilder_.isEmpty()) {
              monitorsBuilder_.dispose();
              monitorsBuilder_ = null;
              monitors_ = other.monitors_;
              bitField0_ = (bitField0_ & ~0x00000010);
              monitorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMonitorsFieldBuilder() : null;
            } else {
              monitorsBuilder_.addAllMessages(other.monitors_);
            }
          }
        }
        if (other.hasVidBitrate()) {
          setVidBitrate(other.getVidBitrate());
        }
        if (other.hasFramerate()) {
          setFramerate(other.getFramerate());
        }
        if (other.hasSamplerate()) {
          setSamplerate(other.getSamplerate());
        }
        if (other.hasAudioBitrate()) {
          setAudioBitrate(other.getAudioBitrate());
        }
        if (other.hasChannelcount()) {
          setChannelcount(other.getChannelcount());
        }
        if (other.hasChannellayout()) {
          setChannellayout(other.getChannellayout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProtoType()) {
          return false;
        }
        if (!hasProtoId()) {
          return false;
        }
        if (!hasUtcTime()) {
          return false;
        }
        if (!hasPPS()) {
          return false;
        }
        if (!hasVidBitrate()) {
          return false;
        }
        if (!hasFramerate()) {
          return false;
        }
        if (!hasSamplerate()) {
          return false;
        }
        if (!hasAudioBitrate()) {
          return false;
        }
        if (!hasChannelcount()) {
          return false;
        }
        if (!hasChannellayout()) {
          return false;
        }
        for (int i = 0; i < getMonitorsCount(); i++) {
          if (!getMonitors(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Nick_Stuff.Protocols.AVInitHP.request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Nick_Stuff.Protocols.AVInitHP.request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protoType_ ;
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public int getProtoType() {
        return protoType_;
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }

      private long protoId_ ;
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public boolean hasProtoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public long getProtoId() {
        return protoId_;
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public Builder setProtoId(long value) {
        bitField0_ |= 0x00000002;
        protoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public Builder clearProtoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        protoId_ = 0L;
        onChanged();
        return this;
      }

      private long utcTime_ ;
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public boolean hasUtcTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public long getUtcTime() {
        return utcTime_;
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public Builder setUtcTime(long value) {
        bitField0_ |= 0x00000004;
        utcTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public Builder clearUtcTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        utcTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pPS_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Video Information
       * </pre>
       *
       * <code>required bytes PPS = 4;</code>
       */
      public boolean hasPPS() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *Video Information
       * </pre>
       *
       * <code>required bytes PPS = 4;</code>
       */
      public com.google.protobuf.ByteString getPPS() {
        return pPS_;
      }
      /**
       * <pre>
       *Video Information
       * </pre>
       *
       * <code>required bytes PPS = 4;</code>
       */
      public Builder setPPS(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pPS_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Video Information
       * </pre>
       *
       * <code>required bytes PPS = 4;</code>
       */
      public Builder clearPPS() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pPS_ = getDefaultInstance().getPPS();
        onChanged();
        return this;
      }

      private java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor> monitors_ =
        java.util.Collections.emptyList();
      private void ensureMonitorsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          monitors_ = new java.util.ArrayList<Nick_Stuff.Protocols.AVInitHP.request.monitor>(monitors_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Nick_Stuff.Protocols.AVInitHP.request.monitor, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder, Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder> monitorsBuilder_;

      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor> getMonitorsList() {
        if (monitorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(monitors_);
        } else {
          return monitorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public int getMonitorsCount() {
        if (monitorsBuilder_ == null) {
          return monitors_.size();
        } else {
          return monitorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Nick_Stuff.Protocols.AVInitHP.request.monitor getMonitors(int index) {
        if (monitorsBuilder_ == null) {
          return monitors_.get(index);
        } else {
          return monitorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder setMonitors(
          int index, Nick_Stuff.Protocols.AVInitHP.request.monitor value) {
        if (monitorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonitorsIsMutable();
          monitors_.set(index, value);
          onChanged();
        } else {
          monitorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder setMonitors(
          int index, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder builderForValue) {
        if (monitorsBuilder_ == null) {
          ensureMonitorsIsMutable();
          monitors_.set(index, builderForValue.build());
          onChanged();
        } else {
          monitorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder addMonitors(Nick_Stuff.Protocols.AVInitHP.request.monitor value) {
        if (monitorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonitorsIsMutable();
          monitors_.add(value);
          onChanged();
        } else {
          monitorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder addMonitors(
          int index, Nick_Stuff.Protocols.AVInitHP.request.monitor value) {
        if (monitorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMonitorsIsMutable();
          monitors_.add(index, value);
          onChanged();
        } else {
          monitorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder addMonitors(
          Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder builderForValue) {
        if (monitorsBuilder_ == null) {
          ensureMonitorsIsMutable();
          monitors_.add(builderForValue.build());
          onChanged();
        } else {
          monitorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder addMonitors(
          int index, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder builderForValue) {
        if (monitorsBuilder_ == null) {
          ensureMonitorsIsMutable();
          monitors_.add(index, builderForValue.build());
          onChanged();
        } else {
          monitorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder addAllMonitors(
          java.lang.Iterable<? extends Nick_Stuff.Protocols.AVInitHP.request.monitor> values) {
        if (monitorsBuilder_ == null) {
          ensureMonitorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, monitors_);
          onChanged();
        } else {
          monitorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder clearMonitors() {
        if (monitorsBuilder_ == null) {
          monitors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          monitorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Builder removeMonitors(int index) {
        if (monitorsBuilder_ == null) {
          ensureMonitorsIsMutable();
          monitors_.remove(index);
          onChanged();
        } else {
          monitorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder getMonitorsBuilder(
          int index) {
        return getMonitorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder getMonitorsOrBuilder(
          int index) {
        if (monitorsBuilder_ == null) {
          return monitors_.get(index);  } else {
          return monitorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public java.util.List<? extends Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder> 
           getMonitorsOrBuilderList() {
        if (monitorsBuilder_ != null) {
          return monitorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(monitors_);
        }
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder addMonitorsBuilder() {
        return getMonitorsFieldBuilder().addBuilder(
            Nick_Stuff.Protocols.AVInitHP.request.monitor.getDefaultInstance());
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder addMonitorsBuilder(
          int index) {
        return getMonitorsFieldBuilder().addBuilder(
            index, Nick_Stuff.Protocols.AVInitHP.request.monitor.getDefaultInstance());
      }
      /**
       * <code>repeated .request.monitor monitors = 5;</code>
       */
      public java.util.List<Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder> 
           getMonitorsBuilderList() {
        return getMonitorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Nick_Stuff.Protocols.AVInitHP.request.monitor, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder, Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder> 
          getMonitorsFieldBuilder() {
        if (monitorsBuilder_ == null) {
          monitorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Nick_Stuff.Protocols.AVInitHP.request.monitor, Nick_Stuff.Protocols.AVInitHP.request.monitor.Builder, Nick_Stuff.Protocols.AVInitHP.request.monitorOrBuilder>(
                  monitors_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          monitors_ = null;
        }
        return monitorsBuilder_;
      }

      private int vidBitrate_ ;
      /**
       * <code>required int32 vid_bitrate = 6;</code>
       */
      public boolean hasVidBitrate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 vid_bitrate = 6;</code>
       */
      public int getVidBitrate() {
        return vidBitrate_;
      }
      /**
       * <code>required int32 vid_bitrate = 6;</code>
       */
      public Builder setVidBitrate(int value) {
        bitField0_ |= 0x00000020;
        vidBitrate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vid_bitrate = 6;</code>
       */
      public Builder clearVidBitrate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        vidBitrate_ = 0;
        onChanged();
        return this;
      }

      private int framerate_ ;
      /**
       * <code>required int32 framerate = 7;</code>
       */
      public boolean hasFramerate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 framerate = 7;</code>
       */
      public int getFramerate() {
        return framerate_;
      }
      /**
       * <code>required int32 framerate = 7;</code>
       */
      public Builder setFramerate(int value) {
        bitField0_ |= 0x00000040;
        framerate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 framerate = 7;</code>
       */
      public Builder clearFramerate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        framerate_ = 0;
        onChanged();
        return this;
      }

      private int samplerate_ ;
      /**
       * <pre>
       *Audio Information
       * </pre>
       *
       * <code>required int32 samplerate = 8;</code>
       */
      public boolean hasSamplerate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *Audio Information
       * </pre>
       *
       * <code>required int32 samplerate = 8;</code>
       */
      public int getSamplerate() {
        return samplerate_;
      }
      /**
       * <pre>
       *Audio Information
       * </pre>
       *
       * <code>required int32 samplerate = 8;</code>
       */
      public Builder setSamplerate(int value) {
        bitField0_ |= 0x00000080;
        samplerate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Audio Information
       * </pre>
       *
       * <code>required int32 samplerate = 8;</code>
       */
      public Builder clearSamplerate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        samplerate_ = 0;
        onChanged();
        return this;
      }

      private int audioBitrate_ ;
      /**
       * <code>required int32 audio_bitrate = 9;</code>
       */
      public boolean hasAudioBitrate() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 audio_bitrate = 9;</code>
       */
      public int getAudioBitrate() {
        return audioBitrate_;
      }
      /**
       * <code>required int32 audio_bitrate = 9;</code>
       */
      public Builder setAudioBitrate(int value) {
        bitField0_ |= 0x00000100;
        audioBitrate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 audio_bitrate = 9;</code>
       */
      public Builder clearAudioBitrate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        audioBitrate_ = 0;
        onChanged();
        return this;
      }

      private int channelcount_ ;
      /**
       * <code>required int32 channelcount = 10;</code>
       */
      public boolean hasChannelcount() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 channelcount = 10;</code>
       */
      public int getChannelcount() {
        return channelcount_;
      }
      /**
       * <code>required int32 channelcount = 10;</code>
       */
      public Builder setChannelcount(int value) {
        bitField0_ |= 0x00000200;
        channelcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channelcount = 10;</code>
       */
      public Builder clearChannelcount() {
        bitField0_ = (bitField0_ & ~0x00000200);
        channelcount_ = 0;
        onChanged();
        return this;
      }

      private long channellayout_ ;
      /**
       * <code>required int64 channellayout = 11;</code>
       */
      public boolean hasChannellayout() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int64 channellayout = 11;</code>
       */
      public long getChannellayout() {
        return channellayout_;
      }
      /**
       * <code>required int64 channellayout = 11;</code>
       */
      public Builder setChannellayout(long value) {
        bitField0_ |= 0x00000400;
        channellayout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 channellayout = 11;</code>
       */
      public Builder clearChannellayout() {
        bitField0_ = (bitField0_ & ~0x00000400);
        channellayout_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:request)
    }

    // @@protoc_insertion_point(class_scope:request)
    private static final Nick_Stuff.Protocols.AVInitHP.request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Nick_Stuff.Protocols.AVInitHP.request();
    }

    public static Nick_Stuff.Protocols.AVInitHP.request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<request>
        PARSER = new com.google.protobuf.AbstractParser<request>() {
      @java.lang.Override
      public request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Nick_Stuff.Protocols.AVInitHP.request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_monitor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_monitor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.Audio Video Initial Packet Host Protoc" +
      "ol.proto\"\270\002\n\007request\022\022\n\nproto_type\030\001 \002(\005" +
      "\022\020\n\010proto_id\030\002 \002(\003\022\020\n\010utc_time\030\003 \002(\003\022\013\n\003" +
      "PPS\030\004 \002(\014\022\"\n\010monitors\030\005 \003(\0132\020.request.mo" +
      "nitor\022\023\n\013vid_bitrate\030\006 \002(\005\022\021\n\tframerate\030" +
      "\007 \002(\005\022\022\n\nsamplerate\030\010 \002(\005\022\025\n\raudio_bitra" +
      "te\030\t \002(\005\022\024\n\014channelcount\030\n \002(\005\022\025\n\rchanne" +
      "llayout\030\013 \002(\003\032D\n\007monitor\022\016\n\006height\030\001 \002(\005" +
      "\022\r\n\005width\030\002 \002(\005\022\032\n\014availability\030\003 \002(\010:\004t" +
      "rueB \n\024Nick_Stuff.ProtocolsB\010AVInitHP"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_descriptor,
        new java.lang.String[] { "ProtoType", "ProtoId", "UtcTime", "PPS", "Monitors", "VidBitrate", "Framerate", "Samplerate", "AudioBitrate", "Channelcount", "Channellayout", });
    internal_static_request_monitor_descriptor =
      internal_static_request_descriptor.getNestedTypes().get(0);
    internal_static_request_monitor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_monitor_descriptor,
        new java.lang.String[] { "Height", "Width", "Availability", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
