// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client Input Protocol.proto

package Nick_Stuff.Protocols;

public final class InputCP {
  private InputCP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 proto_type = 1;</code>
     */
    boolean hasProtoType();
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    int getProtoType();

    /**
     * <code>required int64 proto_id = 2;</code>
     */
    boolean hasProtoId();
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    long getProtoId();

    /**
     * <code>required int64 utc_time = 3;</code>
     */
    boolean hasUtcTime();
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    long getUtcTime();

    /**
     * <code>required int32 hwid = 4;</code>
     */
    boolean hasHwid();
    /**
     * <code>required int32 hwid = 4;</code>
     */
    int getHwid();

    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    boolean hasMouse();
    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    Nick_Stuff.Protocols.InputCP.data.Coordinate getMouse();
    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMouseOrBuilder();

    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate> 
        getMousePressList();
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    Nick_Stuff.Protocols.InputCP.data.Coordinate getMousePress(int index);
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    int getMousePressCount();
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    java.util.List<? extends Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> 
        getMousePressOrBuilderList();
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMousePressOrBuilder(
        int index);

    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    boolean hasKeyPress();
    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    java.lang.String getKeyPress();
    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getKeyPressBytes();

    /**
     * <code>required int32 state_keys = 8;</code>
     */
    boolean hasStateKeys();
    /**
     * <code>required int32 state_keys = 8;</code>
     */
    int getStateKeys();
  }
  /**
   * Protobuf type {@code data}
   */
  public  static final class data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data)
      dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use data.newBuilder() to construct.
    private data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private data() {
      protoType_ = 0;
      protoId_ = 0L;
      utcTime_ = 0L;
      hwid_ = 0;
      mousePress_ = java.util.Collections.emptyList();
      keyPress_ = "";
      stateKeys_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              protoId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              utcTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hwid_ = input.readInt32();
              break;
            }
            case 42: {
              Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = mouse_.toBuilder();
              }
              mouse_ = input.readMessage(Nick_Stuff.Protocols.InputCP.data.Coordinate.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mouse_);
                mouse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                mousePress_ = new java.util.ArrayList<Nick_Stuff.Protocols.InputCP.data.Coordinate>();
                mutable_bitField0_ |= 0x00000020;
              }
              mousePress_.add(
                  input.readMessage(Nick_Stuff.Protocols.InputCP.data.Coordinate.PARSER, extensionRegistry));
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              keyPress_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              stateKeys_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          mousePress_ = java.util.Collections.unmodifiableList(mousePress_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Nick_Stuff.Protocols.InputCP.internal_static_data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Nick_Stuff.Protocols.InputCP.internal_static_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Nick_Stuff.Protocols.InputCP.data.class, Nick_Stuff.Protocols.InputCP.data.Builder.class);
    }

    public interface CoordinateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:data.Coordinate)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required int32 x = 1;</code>
       */
      int getX();

      /**
       * <code>required int32 y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 2;</code>
       */
      int getY();
    }
    /**
     * Protobuf type {@code data.Coordinate}
     */
    public  static final class Coordinate extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:data.Coordinate)
        CoordinateOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Coordinate.newBuilder() to construct.
      private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Coordinate() {
        x_ = 0;
        y_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Coordinate(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Nick_Stuff.Protocols.InputCP.internal_static_data_Coordinate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Nick_Stuff.Protocols.InputCP.internal_static_data_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Nick_Stuff.Protocols.InputCP.data.Coordinate.class, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder.class);
      }

      private int bitField0_;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Nick_Stuff.Protocols.InputCP.data.Coordinate)) {
          return super.equals(obj);
        }
        Nick_Stuff.Protocols.InputCP.data.Coordinate other = (Nick_Stuff.Protocols.InputCP.data.Coordinate) obj;

        boolean result = true;
        result = result && (hasX() == other.hasX());
        if (hasX()) {
          result = result && (getX()
              == other.getX());
        }
        result = result && (hasY() == other.hasY());
        if (hasY()) {
          result = result && (getY()
              == other.getY());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasX()) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + getX();
        }
        if (hasY()) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + getY();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Nick_Stuff.Protocols.InputCP.data.Coordinate parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Nick_Stuff.Protocols.InputCP.data.Coordinate prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code data.Coordinate}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:data.Coordinate)
          Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Nick_Stuff.Protocols.InputCP.internal_static_data_Coordinate_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Nick_Stuff.Protocols.InputCP.internal_static_data_Coordinate_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Nick_Stuff.Protocols.InputCP.data.Coordinate.class, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder.class);
        }

        // Construct using Nick_Stuff.Protocols.InputCP.data.Coordinate.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Nick_Stuff.Protocols.InputCP.internal_static_data_Coordinate_descriptor;
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.InputCP.data.Coordinate getDefaultInstanceForType() {
          return Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance();
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.InputCP.data.Coordinate build() {
          Nick_Stuff.Protocols.InputCP.data.Coordinate result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Nick_Stuff.Protocols.InputCP.data.Coordinate buildPartial() {
          Nick_Stuff.Protocols.InputCP.data.Coordinate result = new Nick_Stuff.Protocols.InputCP.data.Coordinate(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Nick_Stuff.Protocols.InputCP.data.Coordinate) {
            return mergeFrom((Nick_Stuff.Protocols.InputCP.data.Coordinate)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Nick_Stuff.Protocols.InputCP.data.Coordinate other) {
          if (other == Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasX()) {
            return false;
          }
          if (!hasY()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Nick_Stuff.Protocols.InputCP.data.Coordinate parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Nick_Stuff.Protocols.InputCP.data.Coordinate) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int x_ ;
        /**
         * <code>required int32 x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        private int y_ ;
        /**
         * <code>required int32 y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:data.Coordinate)
      }

      // @@protoc_insertion_point(class_scope:data.Coordinate)
      private static final Nick_Stuff.Protocols.InputCP.data.Coordinate DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Nick_Stuff.Protocols.InputCP.data.Coordinate();
      }

      public static Nick_Stuff.Protocols.InputCP.data.Coordinate getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Coordinate>
          PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
        @java.lang.Override
        public Coordinate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Coordinate(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Coordinate> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Coordinate> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.InputCP.data.Coordinate getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PROTO_TYPE_FIELD_NUMBER = 1;
    private int protoType_;
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 proto_type = 1;</code>
     */
    public int getProtoType() {
      return protoType_;
    }

    public static final int PROTO_ID_FIELD_NUMBER = 2;
    private long protoId_;
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    public boolean hasProtoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 proto_id = 2;</code>
     */
    public long getProtoId() {
      return protoId_;
    }

    public static final int UTC_TIME_FIELD_NUMBER = 3;
    private long utcTime_;
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    public boolean hasUtcTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 utc_time = 3;</code>
     */
    public long getUtcTime() {
      return utcTime_;
    }

    public static final int HWID_FIELD_NUMBER = 4;
    private int hwid_;
    /**
     * <code>required int32 hwid = 4;</code>
     */
    public boolean hasHwid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 hwid = 4;</code>
     */
    public int getHwid() {
      return hwid_;
    }

    public static final int MOUSE_FIELD_NUMBER = 5;
    private Nick_Stuff.Protocols.InputCP.data.Coordinate mouse_;
    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    public boolean hasMouse() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    public Nick_Stuff.Protocols.InputCP.data.Coordinate getMouse() {
      return mouse_ == null ? Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance() : mouse_;
    }
    /**
     * <code>required .data.Coordinate mouse = 5;</code>
     */
    public Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMouseOrBuilder() {
      return mouse_ == null ? Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance() : mouse_;
    }

    public static final int MOUSE_PRESS_FIELD_NUMBER = 6;
    private java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate> mousePress_;
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    public java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate> getMousePressList() {
      return mousePress_;
    }
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    public java.util.List<? extends Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> 
        getMousePressOrBuilderList() {
      return mousePress_;
    }
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    public int getMousePressCount() {
      return mousePress_.size();
    }
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    public Nick_Stuff.Protocols.InputCP.data.Coordinate getMousePress(int index) {
      return mousePress_.get(index);
    }
    /**
     * <code>repeated .data.Coordinate mouse_press = 6;</code>
     */
    public Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMousePressOrBuilder(
        int index) {
      return mousePress_.get(index);
    }

    public static final int KEY_PRESS_FIELD_NUMBER = 7;
    private volatile java.lang.Object keyPress_;
    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    public boolean hasKeyPress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    public java.lang.String getKeyPress() {
      java.lang.Object ref = keyPress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          keyPress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key_press = 7 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getKeyPressBytes() {
      java.lang.Object ref = keyPress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyPress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_KEYS_FIELD_NUMBER = 8;
    private int stateKeys_;
    /**
     * <code>required int32 state_keys = 8;</code>
     */
    public boolean hasStateKeys() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 state_keys = 8;</code>
     */
    public int getStateKeys() {
      return stateKeys_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProtoType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtoId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUtcTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHwid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMouse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStateKeys()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMouse().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMousePressCount(); i++) {
        if (!getMousePress(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, protoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, utcTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, hwid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getMouse());
      }
      for (int i = 0; i < mousePress_.size(); i++) {
        output.writeMessage(6, mousePress_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, keyPress_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, stateKeys_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, protoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, utcTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hwid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMouse());
      }
      for (int i = 0; i < mousePress_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, mousePress_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, keyPress_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, stateKeys_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Nick_Stuff.Protocols.InputCP.data)) {
        return super.equals(obj);
      }
      Nick_Stuff.Protocols.InputCP.data other = (Nick_Stuff.Protocols.InputCP.data) obj;

      boolean result = true;
      result = result && (hasProtoType() == other.hasProtoType());
      if (hasProtoType()) {
        result = result && (getProtoType()
            == other.getProtoType());
      }
      result = result && (hasProtoId() == other.hasProtoId());
      if (hasProtoId()) {
        result = result && (getProtoId()
            == other.getProtoId());
      }
      result = result && (hasUtcTime() == other.hasUtcTime());
      if (hasUtcTime()) {
        result = result && (getUtcTime()
            == other.getUtcTime());
      }
      result = result && (hasHwid() == other.hasHwid());
      if (hasHwid()) {
        result = result && (getHwid()
            == other.getHwid());
      }
      result = result && (hasMouse() == other.hasMouse());
      if (hasMouse()) {
        result = result && getMouse()
            .equals(other.getMouse());
      }
      result = result && getMousePressList()
          .equals(other.getMousePressList());
      result = result && (hasKeyPress() == other.hasKeyPress());
      if (hasKeyPress()) {
        result = result && getKeyPress()
            .equals(other.getKeyPress());
      }
      result = result && (hasStateKeys() == other.hasStateKeys());
      if (hasStateKeys()) {
        result = result && (getStateKeys()
            == other.getStateKeys());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtoType()) {
        hash = (37 * hash) + PROTO_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getProtoType();
      }
      if (hasProtoId()) {
        hash = (37 * hash) + PROTO_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getProtoId());
      }
      if (hasUtcTime()) {
        hash = (37 * hash) + UTC_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUtcTime());
      }
      if (hasHwid()) {
        hash = (37 * hash) + HWID_FIELD_NUMBER;
        hash = (53 * hash) + getHwid();
      }
      if (hasMouse()) {
        hash = (37 * hash) + MOUSE_FIELD_NUMBER;
        hash = (53 * hash) + getMouse().hashCode();
      }
      if (getMousePressCount() > 0) {
        hash = (37 * hash) + MOUSE_PRESS_FIELD_NUMBER;
        hash = (53 * hash) + getMousePressList().hashCode();
      }
      if (hasKeyPress()) {
        hash = (37 * hash) + KEY_PRESS_FIELD_NUMBER;
        hash = (53 * hash) + getKeyPress().hashCode();
      }
      if (hasStateKeys()) {
        hash = (37 * hash) + STATE_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getStateKeys();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Nick_Stuff.Protocols.InputCP.data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Nick_Stuff.Protocols.InputCP.data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data)
        Nick_Stuff.Protocols.InputCP.dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Nick_Stuff.Protocols.InputCP.internal_static_data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Nick_Stuff.Protocols.InputCP.internal_static_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Nick_Stuff.Protocols.InputCP.data.class, Nick_Stuff.Protocols.InputCP.data.Builder.class);
      }

      // Construct using Nick_Stuff.Protocols.InputCP.data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMouseFieldBuilder();
          getMousePressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        protoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        utcTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        hwid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (mouseBuilder_ == null) {
          mouse_ = null;
        } else {
          mouseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (mousePressBuilder_ == null) {
          mousePress_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          mousePressBuilder_.clear();
        }
        keyPress_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        stateKeys_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Nick_Stuff.Protocols.InputCP.internal_static_data_descriptor;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.InputCP.data getDefaultInstanceForType() {
        return Nick_Stuff.Protocols.InputCP.data.getDefaultInstance();
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.InputCP.data build() {
        Nick_Stuff.Protocols.InputCP.data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Nick_Stuff.Protocols.InputCP.data buildPartial() {
        Nick_Stuff.Protocols.InputCP.data result = new Nick_Stuff.Protocols.InputCP.data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.protoId_ = protoId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.utcTime_ = utcTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hwid_ = hwid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (mouseBuilder_ == null) {
          result.mouse_ = mouse_;
        } else {
          result.mouse_ = mouseBuilder_.build();
        }
        if (mousePressBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            mousePress_ = java.util.Collections.unmodifiableList(mousePress_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.mousePress_ = mousePress_;
        } else {
          result.mousePress_ = mousePressBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.keyPress_ = keyPress_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.stateKeys_ = stateKeys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Nick_Stuff.Protocols.InputCP.data) {
          return mergeFrom((Nick_Stuff.Protocols.InputCP.data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Nick_Stuff.Protocols.InputCP.data other) {
        if (other == Nick_Stuff.Protocols.InputCP.data.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasProtoId()) {
          setProtoId(other.getProtoId());
        }
        if (other.hasUtcTime()) {
          setUtcTime(other.getUtcTime());
        }
        if (other.hasHwid()) {
          setHwid(other.getHwid());
        }
        if (other.hasMouse()) {
          mergeMouse(other.getMouse());
        }
        if (mousePressBuilder_ == null) {
          if (!other.mousePress_.isEmpty()) {
            if (mousePress_.isEmpty()) {
              mousePress_ = other.mousePress_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureMousePressIsMutable();
              mousePress_.addAll(other.mousePress_);
            }
            onChanged();
          }
        } else {
          if (!other.mousePress_.isEmpty()) {
            if (mousePressBuilder_.isEmpty()) {
              mousePressBuilder_.dispose();
              mousePressBuilder_ = null;
              mousePress_ = other.mousePress_;
              bitField0_ = (bitField0_ & ~0x00000020);
              mousePressBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMousePressFieldBuilder() : null;
            } else {
              mousePressBuilder_.addAllMessages(other.mousePress_);
            }
          }
        }
        if (other.hasKeyPress()) {
          bitField0_ |= 0x00000040;
          keyPress_ = other.keyPress_;
          onChanged();
        }
        if (other.hasStateKeys()) {
          setStateKeys(other.getStateKeys());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProtoType()) {
          return false;
        }
        if (!hasProtoId()) {
          return false;
        }
        if (!hasUtcTime()) {
          return false;
        }
        if (!hasHwid()) {
          return false;
        }
        if (!hasMouse()) {
          return false;
        }
        if (!hasStateKeys()) {
          return false;
        }
        if (!getMouse().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getMousePressCount(); i++) {
          if (!getMousePress(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Nick_Stuff.Protocols.InputCP.data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Nick_Stuff.Protocols.InputCP.data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protoType_ ;
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public int getProtoType() {
        return protoType_;
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 proto_type = 1;</code>
       */
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }

      private long protoId_ ;
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public boolean hasProtoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public long getProtoId() {
        return protoId_;
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public Builder setProtoId(long value) {
        bitField0_ |= 0x00000002;
        protoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 proto_id = 2;</code>
       */
      public Builder clearProtoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        protoId_ = 0L;
        onChanged();
        return this;
      }

      private long utcTime_ ;
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public boolean hasUtcTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public long getUtcTime() {
        return utcTime_;
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public Builder setUtcTime(long value) {
        bitField0_ |= 0x00000004;
        utcTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 utc_time = 3;</code>
       */
      public Builder clearUtcTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        utcTime_ = 0L;
        onChanged();
        return this;
      }

      private int hwid_ ;
      /**
       * <code>required int32 hwid = 4;</code>
       */
      public boolean hasHwid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 hwid = 4;</code>
       */
      public int getHwid() {
        return hwid_;
      }
      /**
       * <code>required int32 hwid = 4;</code>
       */
      public Builder setHwid(int value) {
        bitField0_ |= 0x00000008;
        hwid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hwid = 4;</code>
       */
      public Builder clearHwid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hwid_ = 0;
        onChanged();
        return this;
      }

      private Nick_Stuff.Protocols.InputCP.data.Coordinate mouse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> mouseBuilder_;
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public boolean hasMouse() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate getMouse() {
        if (mouseBuilder_ == null) {
          return mouse_ == null ? Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance() : mouse_;
        } else {
          return mouseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Builder setMouse(Nick_Stuff.Protocols.InputCP.data.Coordinate value) {
        if (mouseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mouse_ = value;
          onChanged();
        } else {
          mouseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Builder setMouse(
          Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder builderForValue) {
        if (mouseBuilder_ == null) {
          mouse_ = builderForValue.build();
          onChanged();
        } else {
          mouseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Builder mergeMouse(Nick_Stuff.Protocols.InputCP.data.Coordinate value) {
        if (mouseBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              mouse_ != null &&
              mouse_ != Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance()) {
            mouse_ =
              Nick_Stuff.Protocols.InputCP.data.Coordinate.newBuilder(mouse_).mergeFrom(value).buildPartial();
          } else {
            mouse_ = value;
          }
          onChanged();
        } else {
          mouseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Builder clearMouse() {
        if (mouseBuilder_ == null) {
          mouse_ = null;
          onChanged();
        } else {
          mouseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder getMouseBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getMouseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMouseOrBuilder() {
        if (mouseBuilder_ != null) {
          return mouseBuilder_.getMessageOrBuilder();
        } else {
          return mouse_ == null ?
              Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance() : mouse_;
        }
      }
      /**
       * <code>required .data.Coordinate mouse = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> 
          getMouseFieldBuilder() {
        if (mouseBuilder_ == null) {
          mouseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder>(
                  getMouse(),
                  getParentForChildren(),
                  isClean());
          mouse_ = null;
        }
        return mouseBuilder_;
      }

      private java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate> mousePress_ =
        java.util.Collections.emptyList();
      private void ensureMousePressIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          mousePress_ = new java.util.ArrayList<Nick_Stuff.Protocols.InputCP.data.Coordinate>(mousePress_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> mousePressBuilder_;

      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate> getMousePressList() {
        if (mousePressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mousePress_);
        } else {
          return mousePressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public int getMousePressCount() {
        if (mousePressBuilder_ == null) {
          return mousePress_.size();
        } else {
          return mousePressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate getMousePress(int index) {
        if (mousePressBuilder_ == null) {
          return mousePress_.get(index);
        } else {
          return mousePressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder setMousePress(
          int index, Nick_Stuff.Protocols.InputCP.data.Coordinate value) {
        if (mousePressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMousePressIsMutable();
          mousePress_.set(index, value);
          onChanged();
        } else {
          mousePressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder setMousePress(
          int index, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder builderForValue) {
        if (mousePressBuilder_ == null) {
          ensureMousePressIsMutable();
          mousePress_.set(index, builderForValue.build());
          onChanged();
        } else {
          mousePressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder addMousePress(Nick_Stuff.Protocols.InputCP.data.Coordinate value) {
        if (mousePressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMousePressIsMutable();
          mousePress_.add(value);
          onChanged();
        } else {
          mousePressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder addMousePress(
          int index, Nick_Stuff.Protocols.InputCP.data.Coordinate value) {
        if (mousePressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMousePressIsMutable();
          mousePress_.add(index, value);
          onChanged();
        } else {
          mousePressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder addMousePress(
          Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder builderForValue) {
        if (mousePressBuilder_ == null) {
          ensureMousePressIsMutable();
          mousePress_.add(builderForValue.build());
          onChanged();
        } else {
          mousePressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder addMousePress(
          int index, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder builderForValue) {
        if (mousePressBuilder_ == null) {
          ensureMousePressIsMutable();
          mousePress_.add(index, builderForValue.build());
          onChanged();
        } else {
          mousePressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder addAllMousePress(
          java.lang.Iterable<? extends Nick_Stuff.Protocols.InputCP.data.Coordinate> values) {
        if (mousePressBuilder_ == null) {
          ensureMousePressIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mousePress_);
          onChanged();
        } else {
          mousePressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder clearMousePress() {
        if (mousePressBuilder_ == null) {
          mousePress_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          mousePressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Builder removeMousePress(int index) {
        if (mousePressBuilder_ == null) {
          ensureMousePressIsMutable();
          mousePress_.remove(index);
          onChanged();
        } else {
          mousePressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder getMousePressBuilder(
          int index) {
        return getMousePressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder getMousePressOrBuilder(
          int index) {
        if (mousePressBuilder_ == null) {
          return mousePress_.get(index);  } else {
          return mousePressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public java.util.List<? extends Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> 
           getMousePressOrBuilderList() {
        if (mousePressBuilder_ != null) {
          return mousePressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mousePress_);
        }
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder addMousePressBuilder() {
        return getMousePressFieldBuilder().addBuilder(
            Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder addMousePressBuilder(
          int index) {
        return getMousePressFieldBuilder().addBuilder(
            index, Nick_Stuff.Protocols.InputCP.data.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .data.Coordinate mouse_press = 6;</code>
       */
      public java.util.List<Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder> 
           getMousePressBuilderList() {
        return getMousePressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder> 
          getMousePressFieldBuilder() {
        if (mousePressBuilder_ == null) {
          mousePressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Nick_Stuff.Protocols.InputCP.data.Coordinate, Nick_Stuff.Protocols.InputCP.data.Coordinate.Builder, Nick_Stuff.Protocols.InputCP.data.CoordinateOrBuilder>(
                  mousePress_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          mousePress_ = null;
        }
        return mousePressBuilder_;
      }

      private java.lang.Object keyPress_ = "";
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public boolean hasKeyPress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public java.lang.String getKeyPress() {
        java.lang.Object ref = keyPress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            keyPress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getKeyPressBytes() {
        java.lang.Object ref = keyPress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyPress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public Builder setKeyPress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        keyPress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public Builder clearKeyPress() {
        bitField0_ = (bitField0_ & ~0x00000040);
        keyPress_ = getDefaultInstance().getKeyPress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key_press = 7 [default = ""];</code>
       */
      public Builder setKeyPressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        keyPress_ = value;
        onChanged();
        return this;
      }

      private int stateKeys_ ;
      /**
       * <code>required int32 state_keys = 8;</code>
       */
      public boolean hasStateKeys() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 state_keys = 8;</code>
       */
      public int getStateKeys() {
        return stateKeys_;
      }
      /**
       * <code>required int32 state_keys = 8;</code>
       */
      public Builder setStateKeys(int value) {
        bitField0_ |= 0x00000080;
        stateKeys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state_keys = 8;</code>
       */
      public Builder clearStateKeys() {
        bitField0_ = (bitField0_ & ~0x00000080);
        stateKeys_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data)
    }

    // @@protoc_insertion_point(class_scope:data)
    private static final Nick_Stuff.Protocols.InputCP.data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Nick_Stuff.Protocols.InputCP.data();
    }

    public static Nick_Stuff.Protocols.InputCP.data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<data>
        PARSER = new com.google.protobuf.AbstractParser<data>() {
      @java.lang.Override
      public data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Nick_Stuff.Protocols.InputCP.data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Coordinate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_Coordinate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033Client Input Protocol.proto\"\341\001\n\004data\022\022" +
      "\n\nproto_type\030\001 \002(\005\022\020\n\010proto_id\030\002 \002(\003\022\020\n\010" +
      "utc_time\030\003 \002(\003\022\014\n\004hwid\030\004 \002(\005\022\037\n\005mouse\030\005 " +
      "\002(\0132\020.data.Coordinate\022%\n\013mouse_press\030\006 \003" +
      "(\0132\020.data.Coordinate\022\023\n\tkey_press\030\007 \001(\t:" +
      "\000\022\022\n\nstate_keys\030\010 \002(\005\032\"\n\nCoordinate\022\t\n\001x" +
      "\030\001 \002(\005\022\t\n\001y\030\002 \002(\005B\037\n\024Nick_Stuff.Protocol" +
      "sB\007InputCP"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_descriptor,
        new java.lang.String[] { "ProtoType", "ProtoId", "UtcTime", "Hwid", "Mouse", "MousePress", "KeyPress", "StateKeys", });
    internal_static_data_Coordinate_descriptor =
      internal_static_data_descriptor.getNestedTypes().get(0);
    internal_static_data_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_Coordinate_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
