// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtocol.proto
package Nick_Stuff.Protocols;

public final class Test_Protocol {
    private Test_Protocol() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface dataChunkOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dataChunk)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string name = 1;</code>
         */
        boolean hasName();
        /**
         * <code>required string name = 1;</code>
         */
        java.lang.String getName();
        /**
         * <code>required string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>required int32 id = 2;</code>
         */
        boolean hasId();
        /**
         * <code>required int32 id = 2;</code>
         */
        int getId();

        /**
         * <code>optional string description = 3;</code>
         */
        boolean hasDescription();
        /**
         * <code>optional string description = 3;</code>
         */
        java.lang.String getDescription();
        /**
         * <code>optional string description = 3;</code>
         */
        com.google.protobuf.ByteString
        getDescriptionBytes();

        /**
         * <code>optional bytes image = 4;</code>
         */
        boolean hasImage();
        /**
         * <code>optional bytes image = 4;</code>
         */
        com.google.protobuf.ByteString getImage();

        /**
         * <code>repeated string text = 5;</code>
         */
        java.util.List<java.lang.String>
        getTextList();
        /**
         * <code>repeated string text = 5;</code>
         */
        int getTextCount();
        /**
         * <code>repeated string text = 5;</code>
         */
        java.lang.String getText(int index);
        /**
         * <code>repeated string text = 5;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes(int index);
    }
    /**
     * Protobuf type {@code dataChunk}
     */
    public  static final class dataChunk extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:dataChunk)
            dataChunkOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use dataChunk.newBuilder() to construct.
        private dataChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private dataChunk() {
            name_ = "";
            id_ = 0;
            description_ = "";
            image_ = com.google.protobuf.ByteString.EMPTY;
            text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private dataChunk(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            name_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            id_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            description_ = bs;
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            image_ = input.readBytes();
                            break;
                        }
                        case 42: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                text_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            text_.add(bs);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    text_ = text_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Test_Protocol.internal_static_dataChunk_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Test_Protocol.internal_static_dataChunk_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Test_Protocol.dataChunk.class, Test_Protocol.dataChunk.Builder.class);
        }

        private int bitField0_;
        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ID_FIELD_NUMBER = 2;
        private int id_;
        /**
         * <code>required int32 id = 2;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int DESCRIPTION_FIELD_NUMBER = 3;
        private volatile java.lang.Object description_;
        /**
         * <code>optional string description = 3;</code>
         */
        public boolean hasDescription() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public java.lang.String getDescription() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    description_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IMAGE_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString image_;
        /**
         * <code>optional bytes image = 4;</code>
         */
        public boolean hasImage() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional bytes image = 4;</code>
         */
        public com.google.protobuf.ByteString getImage() {
            return image_;
        }

        public static final int TEXT_FIELD_NUMBER = 5;
        private com.google.protobuf.LazyStringList text_;
        /**
         * <code>repeated string text = 5;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getTextList() {
            return text_;
        }
        /**
         * <code>repeated string text = 5;</code>
         */
        public int getTextCount() {
            return text_.size();
        }
        /**
         * <code>repeated string text = 5;</code>
         */
        public java.lang.String getText(int index) {
            return text_.get(index);
        }
        /**
         * <code>repeated string text = 5;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes(int index) {
            return text_.getByteString(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, id_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, image_);
            }
            for (int i = 0; i < text_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, text_.getRaw(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, id_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, image_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < text_.size(); i++) {
                    dataSize += computeStringSizeNoTag(text_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getTextList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Test_Protocol.dataChunk)) {
                return super.equals(obj);
            }
            Test_Protocol.dataChunk other = (Test_Protocol.dataChunk) obj;

            boolean result = true;
            result = result && (hasName() == other.hasName());
            if (hasName()) {
                result = result && getName()
                        .equals(other.getName());
            }
            result = result && (hasId() == other.hasId());
            if (hasId()) {
                result = result && (getId()
                        == other.getId());
            }
            result = result && (hasDescription() == other.hasDescription());
            if (hasDescription()) {
                result = result && getDescription()
                        .equals(other.getDescription());
            }
            result = result && (hasImage() == other.hasImage());
            if (hasImage()) {
                result = result && getImage()
                        .equals(other.getImage());
            }
            result = result && getTextList()
                    .equals(other.getTextList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasName()) {
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
            }
            if (hasId()) {
                hash = (37 * hash) + ID_FIELD_NUMBER;
                hash = (53 * hash) + getId();
            }
            if (hasDescription()) {
                hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
                hash = (53 * hash) + getDescription().hashCode();
            }
            if (hasImage()) {
                hash = (37 * hash) + IMAGE_FIELD_NUMBER;
                hash = (53 * hash) + getImage().hashCode();
            }
            if (getTextCount() > 0) {
                hash = (37 * hash) + TEXT_FIELD_NUMBER;
                hash = (53 * hash) + getTextList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Test_Protocol.dataChunk parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Test_Protocol.dataChunk parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Test_Protocol.dataChunk parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Test_Protocol.dataChunk parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Test_Protocol.dataChunk parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Test_Protocol.dataChunk parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Test_Protocol.dataChunk parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Test_Protocol.dataChunk parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static Test_Protocol.dataChunk parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static Test_Protocol.dataChunk parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static Test_Protocol.dataChunk parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static Test_Protocol.dataChunk parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(Test_Protocol.dataChunk prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code dataChunk}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dataChunk)
                Test_Protocol.dataChunkOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Test_Protocol.internal_static_dataChunk_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Test_Protocol.internal_static_dataChunk_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Test_Protocol.dataChunk.class, Test_Protocol.dataChunk.Builder.class);
            }

            // Construct using Test_Protocol.dataChunk.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                description_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                image_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Test_Protocol.internal_static_dataChunk_descriptor;
            }

            @java.lang.Override
            public Test_Protocol.dataChunk getDefaultInstanceForType() {
                return Test_Protocol.dataChunk.getDefaultInstance();
            }

            @java.lang.Override
            public Test_Protocol.dataChunk build() {
                Test_Protocol.dataChunk result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Test_Protocol.dataChunk buildPartial() {
                Test_Protocol.dataChunk result = new Test_Protocol.dataChunk(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.description_ = description_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.image_ = image_;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    text_ = text_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.text_ = text_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Test_Protocol.dataChunk) {
                    return mergeFrom((Test_Protocol.dataChunk)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Test_Protocol.dataChunk other) {
                if (other == Test_Protocol.dataChunk.getDefaultInstance()) return this;
                if (other.hasName()) {
                    bitField0_ |= 0x00000001;
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasDescription()) {
                    bitField0_ |= 0x00000004;
                    description_ = other.description_;
                    onChanged();
                }
                if (other.hasImage()) {
                    setImage(other.getImage());
                }
                if (!other.text_.isEmpty()) {
                    if (text_.isEmpty()) {
                        text_ = other.text_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureTextIsMutable();
                        text_.addAll(other.text_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasName()) {
                    return false;
                }
                if (!hasId()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Test_Protocol.dataChunk parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Test_Protocol.dataChunk) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object name_ = "";
            /**
             * <code>required string name = 1;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string name = 1;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string name = 1;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string name = 1;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>required string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            private int id_ ;
            /**
             * <code>required int32 id = 2;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required int32 id = 2;</code>
             */
            public int getId() {
                return id_;
            }
            /**
             * <code>required int32 id = 2;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000002;
                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required int32 id = 2;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object description_ = "";
            /**
             * <code>optional string description = 3;</code>
             */
            public boolean hasDescription() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>optional string description = 3;</code>
             */
            public java.lang.String getDescription() {
                java.lang.Object ref = description_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        description_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string description = 3;</code>
             */
            public com.google.protobuf.ByteString
            getDescriptionBytes() {
                java.lang.Object ref = description_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    description_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string description = 3;</code>
             */
            public Builder setDescription(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                description_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string description = 3;</code>
             */
            public Builder clearDescription() {
                bitField0_ = (bitField0_ & ~0x00000004);
                description_ = getDefaultInstance().getDescription();
                onChanged();
                return this;
            }
            /**
             * <code>optional string description = 3;</code>
             */
            public Builder setDescriptionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                description_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes image = 4;</code>
             */
            public boolean hasImage() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>optional bytes image = 4;</code>
             */
            public com.google.protobuf.ByteString getImage() {
                return image_;
            }
            /**
             * <code>optional bytes image = 4;</code>
             */
            public Builder setImage(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                image_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes image = 4;</code>
             */
            public Builder clearImage() {
                bitField0_ = (bitField0_ & ~0x00000008);
                image_ = getDefaultInstance().getImage();
                onChanged();
                return this;
            }

            private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureTextIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    text_ = new com.google.protobuf.LazyStringArrayList(text_);
                    bitField0_ |= 0x00000010;
                }
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getTextList() {
                return text_.getUnmodifiableView();
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public int getTextCount() {
                return text_.size();
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public java.lang.String getText(int index) {
                return text_.get(index);
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes(int index) {
                return text_.getByteString(index);
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public Builder setText(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTextIsMutable();
                text_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public Builder addText(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTextIsMutable();
                text_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public Builder addAllText(
                    java.lang.Iterable<java.lang.String> values) {
                ensureTextIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, text_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public Builder clearText() {
                text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string text = 5;</code>
             */
            public Builder addTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTextIsMutable();
                text_.add(value);
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:dataChunk)
        }

        // @@protoc_insertion_point(class_scope:dataChunk)
        private static final Test_Protocol.dataChunk DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Test_Protocol.dataChunk();
        }

        public static Test_Protocol.dataChunk getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<dataChunk>
                PARSER = new com.google.protobuf.AbstractParser<dataChunk>() {
            @java.lang.Override
            public dataChunk parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new dataChunk(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<dataChunk> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<dataChunk> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Test_Protocol.dataChunk getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dataChunk_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_dataChunk_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\022TestProtocol.proto\"W\n\tdataChunk\022\014\n\004nam" +
                        "e\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\023\n\013description\030\003 \001(\t" +
                        "\022\r\n\005image\030\004 \001(\014\022\014\n\004text\030\005 \003(\tB\017B\rTest_Pr" +
                        "otocol"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_dataChunk_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dataChunk_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_dataChunk_descriptor,
                new java.lang.String[] { "Name", "Id", "Description", "Image", "Text", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}